name: Restrict PR to Main from Authorized Users

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  check-user:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from an authorized user
      if: "! contains(['Jaro-c'], github.event.pull_request.user.login)"
      run: |
        echo "Only authorized users can open pull requests to main."
        exit 1
